# Generated by Django 4.2.1 on 2023-05-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='blog_comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
