# Generated by Django 4.2.1 on 2023-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPage', '0002_blogitem_blog_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='blog_description',
            field=models.CharField(max_length=300),
        ),
    ]
