# Generated by Django 4.2.1 on 2023-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPage', '0004_alter_blogitem_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogmedia'),
        ),
    ]
