# Generated by Django 4.2.1 on 2023-05-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPage', '0006_remove_blogitem_blog_image_blogitem_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='blog_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
