# Generated by Django 4.2.1 on 2023-05-22 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('job_requirements', models.CharField(max_length=300)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffdepartment', to='frontend.staffdepartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthstaffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_full_name', models.CharField(max_length=50)),
                ('doctor_email', models.EmailField(max_length=90, unique=True)),
                ('doctor_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='frontend.doctordepartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=70)),
                ('patient_email', models.EmailField(max_length=50)),
                ('patient_contact', models.CharField(max_length=15)),
                ('patient_message', models.TextField()),
                ('appointment_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.doctordepartment')),
                ('doctor_patient_preferred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
