# Generated by Django 4.2.1 on 2023-05-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_healthvacancies_staffdepartment_healthstaff_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordepartment',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='staffdepartment',
            old_name='name',
            new_name='title',
        ),
    ]
