# Generated by Django 4.2.1 on 2023-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_name_doctordepartment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordepartment',
            name='desc',
            field=models.CharField(default='simple/short description for this department', max_length=300),
        ),
    ]
