# Generated by Django 4.2.1 on 2023-05-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_doctordepartment_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordepartment',
            name='department_logo',
            field=models.ImageField(default='health.default', upload_to='department_media'),
        ),
    ]
