# Generated by Django 4.2.1 on 2023-05-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_doctordepartment_department_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordepartment',
            name='department_logo',
        ),
        migrations.AddField(
            model_name='doctordepartment',
            name='icon_name',
            field=models.CharField(default='ri-more-line', help_text='get icon name from https://remixicon.com/icon/more-line', max_length=50),
        ),
    ]
