# Generated by Django 4.2.1 on 2023-05-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_doctordepartment_department_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordepartment',
            name='desc',
            field=models.CharField(default='short info for this department', max_length=300),
        ),
        migrations.AlterField(
            model_name='doctordepartment',
            name='icon_name',
            field=models.CharField(default='ri-more-line', help_text='get icon name from https://remixicon.com/icon/', max_length=50),
        ),
    ]
